name: HW5_CI

on:
  push:
    branches: none # [ "main" ]

  workflow_dispatch:

jobs:
  ext-workflow:
    uses: datasys-classrooms/cs553-fall2022-hw5-workflow/.github/workflows/main.yml@main
    with:
      tag: $GITHUB_RUN_NUMBER
